// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN8sCVs_q7d8nd-ryaztbf4vaZInKLAxc',
    appId: '1:357969371884:web:dfb5e97b499287e3effbc9',
    messagingSenderId: '357969371884',
    projectId: 'ecom-firebase-b9bfd',
    authDomain: 'ecom-firebase-b9bfd.firebaseapp.com',
    storageBucket: 'ecom-firebase-b9bfd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-ZW1fbNACVp_Cfj0MS4NvcOaO3yxlf0',
    appId: '1:357969371884:android:84dbce277482a597effbc9',
    messagingSenderId: '357969371884',
    projectId: 'ecom-firebase-b9bfd',
    storageBucket: 'ecom-firebase-b9bfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-Z1CCGVwhsHkdzVJWNz9s4cxbuSEaDc',
    appId: '1:357969371884:ios:63ebd53a6054712aeffbc9',
    messagingSenderId: '357969371884',
    projectId: 'ecom-firebase-b9bfd',
    storageBucket: 'ecom-firebase-b9bfd.appspot.com',
    iosBundleId: 'com.example.mainEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf-Z1CCGVwhsHkdzVJWNz9s4cxbuSEaDc',
    appId: '1:357969371884:ios:681ef9f391ad4234effbc9',
    messagingSenderId: '357969371884',
    projectId: 'ecom-firebase-b9bfd',
    storageBucket: 'ecom-firebase-b9bfd.appspot.com',
    iosBundleId: 'com.example.mainEcommerce.RunnerTests',
  );
}
